"""removed stats and added more to posts

Revision ID: ba926ca30664
Revises: 4bbdb483a308
Create Date: 2022-06-01 16:26:01.223106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba926ca30664'
down_revision = '4bbdb483a308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.add_column('post', sa.Column('ate', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('active', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('hygiene', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('meds', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'meds')
    op.drop_column('post', 'hygiene')
    op.drop_column('post', 'active')
    op.drop_column('post', 'ate')
    op.create_table('stats',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('moodStat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sleepStat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name='stats_author_fkey'),
    sa.PrimaryKeyConstraint('id', name='stats_pkey')
    )
    # ### end Alembic commands ###
